server:
  port: 7010

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      # uri: mongodb+srv://dashdb:MyDB2023@cluster0.3r3zclg.mongodb.net/?retryWrites=true&w=majority
      database: employee-db

info:
  app:
    name: employee-service
    description: This service is related to employee-service
    version: '@project.version@'
    spring-boot-version: '@project.parent.version@'
    
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'

  health:
    db:
      enabled: true