server:
  port: 7014

info:
  app:
    name: rabbitmq-consumer-service
    description: This service is related to rabbitmq-consumer-service
    version: '@project.version@'
    spring-boot-version: '@project.parent.version@'
    
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'

  health:
    db:
      enabled: true

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    

rabbitmq:
  queueName: spring_boot_queue
  exchangeName: spring_boot_exchange
  routingKey: spring_boot_routing_key
